### ISSUE TITLE
Worktime | Add a timer

### ISSUE THREAD

**Issue by YounesBessa** [onRuntime/onruntime-discord-bot#4]
Ce serait peut etre bien si c'est faisable d'ajouter un timer en temps réel qui te dit depuis combien de temps t'es en activité
On pourrait le mettre dans la sidebar, au dessus de ça par exemple
<img width="232" alt="image" src="https://user-images.githubusercontent.com/59099468/198549593-304dea1a-4d5b-4bbf-94c5-65cb91391402.png">

**Comment by AntoineKM** [comment]
T'aurais un exemple de d'autre bot discord qui fait un truc du même style ?
